language: php

services: mongodb

matrix:
  include:
    - php: 7.3
      dist: bionic
      sudo: false
      env: PHPVER=PHP73
    - php: 7.4
      dist: bionic
      sudo: false
      env: PHPVER=PHP74
          
install:
    - ./.travis/install.sh

script: vendor/bin/phpunit
