language: php

services: mongodb

matrix:
  include:
    - php: 7.2
      dist: trusty
      sudo: false
      env: PHPVER=PHP72
          
install:
    - ./.travis/install.sh

script: vendor/bin/phpunit
