language: php

services: mongodb

sudo: false

php:
  - 5.6
  - 7.0

before_script:
  - yes "" | pecl install mongodb
  - yes "" | pecl install APCu || true
  - echo 'extension = apc.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'apc.enabled = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'apc.enable_cli = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - ./composer.phar install

script: vendor/bin/phpunit
