language: php

services: mongodb

sudo: false

php:
  - 7.1
  - 7.0
  - 5.6

before_script:
  - yes "" | pecl install mongodb
  - php --version | grep 7.1 && yes "" | pecl install apcu-5.1.8  || true
  - php --version | grep 7.0 && yes "" | pecl install apcu-5.1.8  || true
  - php --version | grep 5.6 && yes "" | pecl install apcu-4.0.11 || true
  - echo 'extension = apcu.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'apc.enabled = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'apc.enable_cli = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - ./composer.phar install

script: vendor/bin/phpunit
