language: php

services: mongodb

matrix:
  include:
    - php: 7.1
      dist: trusty
      sudo: false
      env: PHPVER=PHP71
    - php: 7.0
      dist: trusty
      sudo: false
      env: PHPVER=PHP70
    - php: 5.6
      dist: trusty
      sudo: false
      env: PHPVER=PHP56
          
install:
    - ./.travis/install.sh

script: vendor/bin/phpunit
